services:
  back-office:
    build:
      context: ./back-office
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    networks:
      - app_network

  db:
    image: mysql:8.0
    environment:
        MYSQL_DATABASE: face_recognize
        MYSQL_ROOT_PASSWORD: ""  
        MYSQL_USER: root
        MYSQL_PASSWORD: ""
        MYSQL_ROOT_HOST: '%'
    volumes:
    - mysql_data:/var/lib/mysql
    - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    networks:
      - app_network
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    command: python main.py
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=mysql://root@db:3306/face_recognize

    networks:
      - app_network



volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge