services:
  rtmp-server:
    image: alfg/nginx-rtmp
    ports:
      - "1935:1935"
      - "8080:80"
    volumes:
      - ./nginx.conf:/opt/nginx/nginx.conf:ro
      - ./mime.types:/opt/nginx/mime.types:ro
    command: ["/bin/sh", "-c", "nginx -g 'daemon off;' -c /opt/nginx/nginx.conf"]
    restart: always
    networks:
      - app_network
  back-office:
    build:
      context: ./back-office
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    networks:
      - app_network
    restart: always

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: face_recognize
      MYSQL_USER: cafadmin
      MYSQL_PASSWORD: caftananarive2025
      MYSQL_ROOT_PASSWORD: caftananarive2025
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    networks:
      - app_network
    restart: always

  back-end:
    build:
      context: ./Back-end
      dockerfile: Dockerfile
    command: python main.py
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=mysql://cafadmin:caftananarive2025@db:3306/face_recognize

    networks:
      - app_network
    restart: always

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
