
FROM python:3.10-slim


WORKDIR /app


ENV PYTHONDONTWRITEBYTECODE 1

ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y --no-install-recommends \
    cmake \
    build-essential \
    libgl1-mesa-glx \
    libffi-dev \
    pkg-config \
    libglib2.0-0 \
    default-libmysqlclient-dev 
    
COPY requirements.txt /app

# RUN pip install --upgrade pip setuptools wheel

RUN pip install  --timeout=120  -r requirements.txt

COPY ./ /app

RUN ls -la /app

EXPOSE 5000

CMD ["flask","run"]
